services:
  issuer-simulator:
    image: issuer-simulator:local
    build:
      context: .
    environment:
      SERVER_PORT: 8090
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
    ports: ["8090:8090"]
networks:
  default:
    name: acquiring-net